### ISSUE TITLE
Strapi models

### ISSUE THREAD

**Issue by joeyfezster** [erikvullings/strapi-to-typescript#8]
Hi Folks, 

First of all, thanks sooo much for this!!
You're doing great work.

I'm not sure if this is the right method to communicate/ask for a feature, but here goes:
I see that strapi models like `user`, `file`, `role` and I have some questions about them:

1. Some of the fields are required, but perhaps they shouldn't be, for example `permissions` and `users` below.
1. Is there a config to capitalize them?
  I'm currently managing to capitalize `interface` names with `interfaceName: (name) => '${name}'`, but this did nothing for the strapi stuff I mentioned.

my role.ts:
```ts
import { permission } from './permission';
import { user } from './user';

/**
 * Model definition for role
 */
export interface role {  // as opposed to Role
  id: string;
  name: string;
  description?: string;
  type?: string;
  permissions: permission[];
  users: user[];
}
```

For context,
I'm writing a script to upload seed data to strapi, and some things like uploading a `user` that has a `role`, but a `role` has an array of `user[]`, which makes it cyclical and tough to manage. In fact, if the `user[]` attribute was optional (which it is in terms of strapi's API - it only requires the `id`), then it would be significantly easier to do this task.

Thanks!

**Comment by aperron** [comment]
Hi,

to answer your questions:
1. Array are not optional because Strapi send array empty, not undefined or null (i don't use GraphQL personally). Maybe an option in the configuration for this behavior would be useful.
2. Have you tried something like:
    `interfaceName: (name) => name.charAt(0).toUpperCase() + name.slice(1),` => `export interface Role { ...`
or
    `interfaceName: (name) => name.toUpperCase(),`  => `export interface ROLE {...`
Maybe I don't quite understand your need.

I also had the need to import data when starting Strapi with an empty database. I wrote a function in `config/functions/bootstrap.js` for this. I can share some of this if you need to.

Thanks for your feedback

**Comment by aperron** [comment]
I add a new option for collection. see v2.0.1
